version: '3.8'

services:
  service1:
    build: ./service_1
    container_name: service1
    expose:
      - "8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 3

  service2:
    build: ./service_2
    container_name: service2
    expose:
      - "5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    build: ./nginx
    container_name: nginx_reverse_proxy
    ports:
      - "8080:80"
    depends_on:
      service1:
        condition: service_healthy
      service2:
        condition: service_healthy

